"""Original English DefineFont3 conversion. No CR2W writer/import/deployment.

Requires fonttools 4.60.1, uharfbuzz 0.56.3 and the separately licensed source
inputs. Writes only a fresh build directory. Standard SWF tags follow Adobe
SWF19; every emitted glyph is independently checked through JPEXS XML.
"""
import argparse
import hashlib
import importlib.util
import json
import math
from pathlib import Path
import struct
import subprocess
import xml.etree.ElementTree as ET
import zlib

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('prep', ROOT / 'tools/prepare-english-gentium.py')
prep = importlib.util.module_from_spec(spec)
spec.loader.exec_module(prep)
audit = prep.audit
BASELINE_SHA = 'a1223e1a26e0c541a69cb1c6ad8bffbd70c074f1d4603193758b2bf220e95f81'
SIL_HASHES = {'Regular': '2027f6a864e5a9907c113438969d1d03fa91dfdd1a3885fa0fdeb496f0f682e4',
              'Italic': 'ed128fd9370533c796219d48aaf17b55d0562791f8cc49e83a6c607c5680bea2',
              'Bold': 'ed788447ea4298dd44ac62034b9a6849003bdfea256757cb4a5d599c8b09a365'}


class Bits:
    def __init__(self):
        self.bits = []

    def put(self, value, count, signed=False):
        low = -(1 << (count - 1)) if signed else 0
        high = (1 << (count - (1 if signed else 0))) - 1
        if count < 1 or not low <= value <= high:
            raise ValueError('Out of range bit field')
        value &= (1 << count) - 1
        self.bits.extend((value >> i) & 1 for i in range(count - 1, -1, -1))

    def bytes(self):
        b = self.bits + [0] * ((-len(self.bits)) % 8)
        return bytes(sum(b[i+j] << (7-j) for j in range(8)) for i in range(0, len(b), 8))


def signed_bits(values):
    return max(1, max((abs(v).bit_length() + 1 for v in values), default=1))


def encode_rect(bounds):
    bits = Bits()
    n = signed_bits(bounds)
    if n > 31:
        raise ValueError('RECT overflow')
    bits.put(n, 5)
    for v in bounds:
        bits.put(v, n, True)
    return bits.bytes()


def shape(records):
    bits = Bits()
    bits.put(1, 4); bits.put(0, 4)
    x = y = 0
    first = True
    for kind, points in records:
        if kind == 'M':
            x, y = points
            bits.put(0, 1); bits.put(3 if first else 1, 5)
            n = signed_bits(points)
            bits.put(n, 5); bits.put(x, n, True); bits.put(y, n, True)
            if first:
                bits.put(1, 1)
            first = False
        elif kind == 'L':
            dx, dy = points[0]-x, points[1]-y
            if dx == dy == 0:
                continue
            n = max(2, signed_bits((dx, dy)))
            if n > 17:
                raise ValueError('Straight edge overflow')
            bits.put(1, 1); bits.put(1, 1); bits.put(n-2, 4); bits.put(1, 1)
            bits.put(dx, n, True); bits.put(dy, n, True)
            x, y = points
        elif kind == 'Q':
            cx, cy, ax, ay = points
            deltas = cx-x, cy-y, ax-cx, ay-cy
            n = max(2, signed_bits(deltas))
            if n > 17:
                raise ValueError('Quadratic edge overflow')
            bits.put(1, 1); bits.put(0, 1); bits.put(n-2, 4)
            for d in deltas:
                bits.put(d, n, True)
            x, y = ax, ay
        else:
            raise ValueError('Unsupported curve record')
    bits.put(0, 6)
    return bits.bytes()


def tag(code, payload):
    return struct.pack('<HI', (code << 6) | 63, len(payload)) + payload


def swf(resource, replacements=None, names=None):
    offset, _, tags = audit.swf_tags(resource)
    raw = resource[offset:]
    body = zlib.decompress(raw[8:]) if raw[:1] == b'C' else raw[8:]
    rect_size = (5 + 4 * (body[0] >> 3) + 7) // 8
    result = body[:rect_size + 4]
    for code, payload in tags:
        if code == 1000:
            continue  # GFx exporter descriptor is regenerated by official importer.
        if code == 75 and replacements:
            fid = struct.unpack_from('<H', payload)[0]
            payload = replacements[fid]
        result += tag(code, payload)
        if code == 75 and names:
            fid = struct.unpack_from('<H', payload)[0]
            result += tag(88, struct.pack('<H', fid) + names[fid].encode() + b'\0' +
                          b'Derived from SIL Global Gentium Book 7.000; U+212E from Noto Project Authors; SIL OFL 1.1.\0')
    return b'CWS' + raw[3:4] + struct.pack('<I', len(result)+8) + zlib.compress(result)


def derive_font(source, noto, destination, style):
    from fontTools.ttLib import TTFont
    from fontTools.pens.recordingPen import DecomposingRecordingPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.pens.ttGlyphPen import TTGlyphPen
    f, nf = TTFont(source), TTFont(noto)
    gs, ngs = f.getGlyphSet(), nf.getGlyphSet()
    cmap, ncmap = f.getBestCmap(), nf.getBestCmap()
    upem = f['head'].unitsPerEm
    added = {}

    def build(code, parts, advance, description):
        pen = TTGlyphPen(None)
        for glyphset, name, transform in parts:
            record = DecomposingRecordingPen(glyphset)
            glyphset[name].draw(record)
            record.replay(TransformPen(pen, transform))
        name = 'quietfolio_' + format(code, '04X')
        glyph = pen.glyph()
        order = list(f.getGlyphOrder())
        f['glyf'][name] = glyph
        f.setGlyphOrder(order + [name])
        glyph.recalcBounds(f['glyf'])
        f['hmtx'][name] = (round(advance), glyph.xMin)
        added[code] = name
        return dict(code=f'U+{code:04X}', construction=description, advance=round(advance))

    result = []
    def adv(code):
        return f['hmtx'][cmap[code]][0]
    ident = (1,0,0,1,0,0)
    for code, components, description in (
            (0x0149, (0x02BC, ord('n')), 'Unicode compatibility composition modifier apostrophe + n'),
            (0x2103, (0x00B0, ord('C')), 'degree + capital C'),
            (0x2109, (0x00B0, ord('F')), 'degree + capital F')):
        first, second = components
        result.append(build(code, [(gs,cmap[first],ident), (gs,cmap[second],(1,0,0,1,adv(first),0))],
                            adv(first)+adv(second), description))
    # Conventional diagonal c/o; component scaling belongs to this symbol only.
    cadvance = adv(ord('c')) * .65
    ox = cadvance + adv(ord('/')) * .45
    result.append(build(0x2105, [(gs,cmap[ord('c')],(.65,0,0,.65,0,upem*.28)),
                                (gs,cmap[ord('/')],(.8,0,0,.8,cadvance-upem*.16,0)),
                                (gs,cmap[ord('o')],(.65,0,0,.65,ox,-upem*.08))],
                        ox + adv(ord('o'))*.65, 'original diagonal care-of c/o composition'))
    added[0x212B] = cmap[0x00C5]
    result.append(dict(code='U+212B', construction='canonical Unicode equivalent U+00C5', advance=adv(0x00C5)))
    if 0x212E not in ncmap:
        raise ValueError('Licensed estimated-symbol source missing')
    scale = upem / nf['head'].unitsPerEm
    result.append(build(0x212E, [(ngs,ncmap[0x212E],(scale,0,0,scale,0,0))],
                        nf['hmtx'][ncmap[0x212E]][0]*scale, 'independent Noto Sans estimated symbol, same style'))
    for table in f['cmap'].tables:
        if table.isUnicode():
            table.cmap.update(added)
    # Derived family identity avoids the Reserved Font Names Gentium and SIL.
    for name_id in (1,3,4,6,16):
        value = ('QuietFolioBook-' + style) if name_id in (3,6) else ('Quiet Folio Book ' + style if name_id == 4 else 'Quiet Folio Book')
        f['name'].setName(value, name_id, 3, 1, 0x409)
        f['name'].setName(value, name_id, 1, 0, 0)
    f.recalcTimestamp = False
    f.save(destination)
    return result


def collect_glyph(font, name):
    from fontTools.pens.basePen import BasePen
    from fontTools.pens.boundsPen import BoundsPen
    scale = 20480 / font['head'].unitsPerEm
    class Pen(BasePen):
        def __init__(self, gs):
            super().__init__(gs)
            self.records = []
        def point(self, p):
            return round(p[0]*scale), round(-p[1]*scale)
        def _moveTo(self, p):
            self.start = self.point(p); self.end = self.start
            self.records.append(('M', self.start))
        def _lineTo(self, p):
            self.end = self.point(p); self.records.append(('L',self.end))
        def _qCurveToOne(self, c, p):
            self.end = self.point(p); self.records.append(('Q',self.point(c)+self.end))
        def _curveToOne(self, *points):
            raise ValueError('Cubic curves unsupported; independently convert first')
        def _closePath(self):
            if self.end != self.start:
                self.records.append(('L',self.start))
        def _endPath(self):
            raise ValueError('Open glyph contour')
    gs = font.getGlyphSet()
    pen = Pen(gs)
    gs[name].draw(pen)
    bounds = BoundsPen(None)
    opened = False
    for kind, p in pen.records:
        if kind == 'M':
            if opened: bounds.closePath()
            bounds.moveTo(p); opened = True
        elif kind == 'L': bounds.lineTo(p)
        else: bounds.qCurveTo(p[:2],p[2:])
    if opened: bounds.closePath()
    b = bounds.bounds
    rect = (math.floor(b[0]),math.ceil(b[2]),math.floor(b[1]),math.ceil(b[3])) if b else (0,0,0,0)
    return pen.records, rect


def kerning(font_path, codes):
    import uharfbuzz as hb
    from fontTools.ttLib import TTFont
    font = TTFont(font_path)
    data = font_path.read_bytes()
    upem = font['head'].unitsPerEm
    hbfont = hb.Font(hb.Face(data)); hbfont.scale = (upem,upem)
    features = {}
    for table in ('GPOS','GSUB'):
        for r in font[table].table.FeatureList.FeatureRecord:
            features[r.FeatureTag] = False
    features['kern'] = True
    cmap = font.getBestCmap()
    advances = {c:font['hmtx'][cmap[c]][0] for c in codes}
    glyphs = {c:font.getGlyphID(cmap[c]) for c in codes}
    pairs, unsupported = [], []
    for a in codes:
        for b in codes:
            buf = hb.Buffer(); buf.add_codepoints([a,b]); buf.guess_segment_properties()
            buf.direction = 'ltr'; buf.language = 'en'
            # Keep soft hyphen's real glyph for metric enumeration, not invisibility.
            buf.flags = hb.BufferFlags.PRESERVE_DEFAULT_IGNORABLES
            hb.shape(hbfont,buf,features)
            infos, pos = buf.glyph_infos, buf.glyph_positions
            if [x.codepoint for x in infos] != [glyphs[a],glyphs[b]]:
                unsupported.append([a,b,'substitution']); continue
            adjustment = pos[0].x_advance - advances[a]
            if (pos[1].x_advance != advances[b] or any(p.x_offset or p.y_offset or p.y_advance for p in pos)):
                unsupported.append([a,b,'placement']); continue
            if adjustment:
                pairs.append((a,b,round(adjustment*20480/upem)))
    if unsupported:
        raise ValueError('GPOS pair cannot be represented by DefineFont3: ' + str(unsupported[:8]))
    if len(pairs) > 65535:
        raise ValueError('Too many SWF kerning pairs')
    return pairs, features


def font_payload(baseline, source, font_id):
    from fontTools.ttLib import TTFont
    f = TTFont(source)
    cmap = f.getBestCmap()
    info = prep.layout(baseline)
    codes = info['codes']
    if len(codes) != 383 or codes != sorted(set(codes)) or set(codes)-set(cmap):
        raise ValueError('Incomplete or unordered baseline coverage')
    glyphs, bounds, advances, records = [], [], [], []
    for c in codes:
        r, rect = collect_glyph(f,cmap[c])
        if not r and c not in (32,160):
            raise ValueError('Empty visible glyph: U+' + format(c,'04X'))
        if r and not any(k in ('L','Q') for k,p in r):
            raise ValueError('No glyph edges')
        records.append(r); glyphs.append(shape(r)); bounds.append(rect)
        advance = round(f['hmtx'][cmap[c]][0]*20480/f['head'].unitsPerEm)
        if not 0 < advance <= 32767:
            raise ValueError('Invalid glyph advance')
        advances.append(advance)
    pairs, features = kerning(source,codes)
    header_end = 7 + baseline[4]
    header = bytearray(baseline[:header_end]); header[2] |= 8
    offset = (len(codes)+1)*4
    offsets = []
    for g in glyphs:
        offsets.append(offset); offset += len(g)
    metrics = (round(f['hhea'].ascent*20480/f['head'].unitsPerEm),
               round(-f['hhea'].descent*20480/f['head'].unitsPerEm),
               round(f['hhea'].lineGap*20480/f['head'].unitsPerEm))
    payload = bytes(header)+struct.pack('<'+'I'*(len(codes)+1),*offsets,offset)+b''.join(glyphs)
    payload += struct.pack('<'+'H'*len(codes),*codes)+struct.pack('<HHh',*metrics)
    payload += struct.pack('<'+'h'*len(codes),*advances)+b''.join(encode_rect(b) for b in bounds)
    payload += struct.pack('<H',len(pairs))+b''.join(struct.pack('<HHh',*p) for p in pairs)
    decoded = prep.layout(payload)
    if decoded['codes'] != codes or decoded['advances'] != advances or decoded['kerning_count'] != len(pairs):
        raise ValueError('Font layout roundtrip failed')
    stats = dict(font_id=font_id,codes=codes,glyphs=383,visible_nonempty=381,spacing_glyphs=[32,160],
                 metrics=metrics,kerning_count=len(pairs),gpos_features=features,
                 min_y=min(b[2] for b in bounds),max_y=max(b[3] for b in bounds),
                 outlines_sha256=audit.sha(b''.join(glyphs)),payload_sha256=audit.sha(payload))
    return payload, stats, records, bounds, advances, pairs


def verify_xml(path, expected, bindings=None):
    """Independent glyph validation; default bindings preserve the v1 contract."""
    if bindings is None:
        bindings = {i: (r'PF Din Text Cond Pro\u0000', i == 3, i == 5) for i in (1,3,5)}
    root = ET.parse(path).getroot()
    fonts = [n for n in root.iter() if n.get('type')=='DefineFont3Tag']
    if len(fonts) != len(expected):
        raise ValueError('Independent font count mismatch')
    if sorted(int(n.get('fontID')) for n in fonts) != sorted(expected):
        raise ValueError('Independent font IDs missing or duplicated')
    for node in fonts:
        fid = int(node.get('fontID'))
        if fid not in bindings or node.get('fontName') != bindings[fid][0]:
            raise ValueError('Runtime font alias/ID changed')
        if (node.get('fontFlagsItalic') == 'true') != bindings[fid][1] or (node.get('fontFlagsBold') == 'true') != bindings[fid][2]:
            raise ValueError('Runtime style binding changed')
        stats, records, bounds, advances, pairs = expected[fid]
        codes = [int(c.text) for c in node.find('codeTable')]
        if codes != stats['codes'] or [int(c.text) for c in node.find('fontAdvanceTable')] != advances:
            raise ValueError('Independent code/advance mismatch')
        if [int(node.get(k)) for k in ('fontAscent','fontDescent','fontLeading')] != list(stats['metrics']):
            raise ValueError('Independent vertical metric mismatch')
        actual_pairs = [(int(n.get('fontKerningCode1')),int(n.get('fontKerningCode2')),int(n.get('fontKerningAdjustment'))) for n in node.find('fontKerningTable')]
        if actual_pairs != pairs:
            raise ValueError('Independent kerning mismatch')
        for i,g in enumerate(node.find('glyphShapeTable')):
            actual = []; x=y=0
            for r in g.find('shapeRecords'):
                kind = r.get('type')
                if kind=='StyleChangeRecord' and r.get('stateMoveTo')=='true':
                    x,y=int(r.get('moveDeltaX')),int(r.get('moveDeltaY')); actual.append(('M',(x,y)))
                elif kind=='StraightEdgeRecord':
                    x+=int(r.get('deltaX','0')); y+=int(r.get('deltaY','0')); actual.append(('L',(x,y)))
                elif kind=='CurvedEdgeRecord':
                    cx,cy=x+int(r.get('controlDeltaX')),y+int(r.get('controlDeltaY'))
                    x,y=cx+int(r.get('anchorDeltaX')),cy+int(r.get('anchorDeltaY'))
                    actual.append(('Q',(cx,cy,x,y)))
            wanted = []; px=py=0
            for k,p in records[i]:
                if k!='L' or tuple(p)!=(px,py): wanted.append((k,tuple(p)))
                px,py=p[-2:]
            if actual != wanted:
                raise ValueError('Independent outline mismatch: ' + str((fid,i)))
        for i,b in enumerate(node.find('fontBoundsTable')):
            if tuple(int(b.get(k)) for k in ('Xmin','Xmax','Ymin','Ymax')) != tuple(bounds[i]):
                raise ValueError('Independent bounds mismatch')


def main():
    import fontTools
    import uharfbuzz
    if fontTools.__version__ != '4.60.1' or uharfbuzz.__version__ != '0.56.3':
        raise ValueError('Reproducible conversion requires fonttools 4.60.1 and uharfbuzz 0.56.3')
    ap = argparse.ArgumentParser()
    ap.add_argument('--game',type=Path,required=True)
    ap.add_argument('--sources',type=Path,required=True)
    ap.add_argument('--noto',type=Path,required=True)
    ap.add_argument('--ffdec',type=Path,required=True)
    ap.add_argument('--out',type=Path,required=True)
    a=ap.parse_args()
    out=a.out.resolve()
    if ROOT/'build' not in out.parents or out.exists(): raise ValueError('Fresh private output required')
    bundle=a.game/'content/content0/bundles/r4gui.bundle'
    entries=[e for e in audit.entries(bundle) if e['resource']==prep.KEY]
    if len(entries)!=1 or entries[0]['codec']!=1: raise ValueError('Current EN entry mismatch')
    e=entries[0]
    with bundle.open('rb') as f:
        f.seek(e['offset']); runtime=zlib.decompress(f.read(e['packed']))
    if audit.sha(runtime)!=BASELINE_SHA: raise ValueError('Current runtime changed; audit first')
    provenance=json.loads((a.noto/'provenance.json').read_text())
    pins=json.loads((ROOT/'src/fonts/noto-estimated-source.json').read_text())
    if provenance != pins: raise ValueError('Noto provenance does not match pinned independent source')
    for file,metadata in provenance['files'].items():
        if audit.sha((a.noto/file).read_bytes())!=metadata['sha256']: raise ValueError('Noto source changed')
    out.mkdir()
    notices = {'OFL-SIL.txt': a.sources/'OFL.txt', 'OFL-Noto.txt': a.noto/'OFL.txt'}
    if audit.sha(notices['OFL-SIL.txt'].read_bytes()) != 'dcae5818b104b6cb24334bb4c92f7896d1ac988529ca4654ff21361a7b5b94ee':
        raise ValueError('Independent SIL OFL notice changed')
    for filename, source in notices.items():
        (out/filename).write_bytes(source.read_bytes())
    (out/'FONT-NOTICES.txt').write_text('Quiet Folio Book: original derivative of SIL Global Gentium Book 7.000.\n'
        'U+212E uses the corresponding Noto Sans style; all other added glyphs use licensed Gentium components.\n'
        'Both sources and this derivative are SIL OFL 1.1; see OFL-SIL.txt and OFL-Noto.txt.\n'
        'Gentium and SIL are reserved names; the derivative family is Quiet Folio Book.\n'
        'PF Din Text Cond Pro is retained only as the required game lookup alias.\n')
    (out/'fonts_en.redswf').write_bytes(runtime)
    inputs=out/'input'; inputs.mkdir()
    (inputs/'fonts_en_qf_unchanged.swf').write_bytes(swf(runtime))
    expected={}; replacements={}; styles=[]; names={}
    font_tags = [(c,b) for c,b in audit.swf_tags(runtime)[2] if c==75]
    if [struct.unpack_from('<H', b)[0] for c,b in font_tags] != [1,3,5]:
        raise ValueError('Expected exactly Regular/Italic/Bold IDs 1/3/5')
    for (code,payload),style in zip(font_tags,('Regular','Italic','Bold')):
        source=a.sources/('GentiumBook-'+style+'.ttf')
        if audit.sha(source.read_bytes())!=SIL_HASHES[style]: raise ValueError('Independent SIL source changed')
        fid=struct.unpack_from('<H',payload)[0]
        derived=out/('QuietFolioBook-'+style+'.ttf')
        additions=derive_font(source,a.noto/('NotoSans-'+style+'.ttf'),derived,style)
        new,stats,records,bounds,advances,pairs=font_payload(payload,derived,fid)
        replacements[fid]=new; expected[fid]=(stats,records,bounds,advances,pairs)
        names[fid]='Quiet Folio Book '+style
        stats.update(style=style,constructions=additions,ttf_sha256=audit.sha(derived.read_bytes()))
        styles.append(stats)
    final=inputs/'fonts_en_qf_book_v1.swf'; final.write_bytes(swf(runtime,replacements,names))
    jar=a.ffdec.resolve()
    result=subprocess.run(['java','-jar',str(jar),'-swf2xml',str(final),str(out/'candidate.xml')],capture_output=True,timeout=60)
    (out/'jpexs.log').write_bytes(result.stdout+result.stderr)
    if result.returncode: raise ValueError('Independent JPEXS decode failed')
    verify_xml(out/'candidate.xml',expected)
    original=[(c,b) for c,b in audit.swf_tags(runtime)[2] if c not in (75,1000)]
    modified=[(c,b) for c,b in audit.swf_tags(final.read_bytes())[2] if c not in (75,88)]
    if original!=modified: raise ValueError('Non-font contracts changed')
    receipt=dict(status='validated native SWF source; official import/cook pending',runtime_sha256=BASELINE_SHA,
                 resource_key=prep.KEY,styles=styles,noto=provenance,independent_xml_geometry_metrics_verified=True,
                 nonfont_tags_identical=True,alignment_zones='none in runtime baseline; no stale zones copied',
                 candidate_path=str(final),candidate_sha256=audit.sha(final.read_bytes()),
                 control_path=str(inputs/'fonts_en_qf_unchanged.swf'),control_sha256=audit.sha((inputs/'fonts_en_qf_unchanged.swf').read_bytes()),
                 cooked=False,package_path=None,runtime_tested=False)
    (out/'receipt.json').write_text(json.dumps(receipt,indent=2))
    print(json.dumps({k:v for k,v in receipt.items() if k not in ('styles','noto')},indent=2))


if __name__=='__main__': main()
